### ISSUE TITLE
Backspace not working properly

### ISSUE THREAD

**Issue by lyrics1988123** [brad28b/meshtastic-cli-chat#1]
Hello, 

i love it, its a cool project, thanks for sharing!
But i do have issues with the backspace, i cannot delete text in the input field, it moves to the right in a weird way. 
Im using windows/powershell.

**Comment by brad28b** [comment]
Hi,

Thanks for reporting the issue. I've updated the repository with the fixed code, please re-clone to get latest version, and confirm working now? 

Thanks
